version: '3.8'

services:
  postgres:
    container_name: Canil-Helkeys
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: canil_helkeys
      PGDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres